[core]
reloadable = true
order = 0

[package]
# Loads models from: https://shapenet.org/
version = "2.1.1"
title = "Isaac Shapenet"
category = "Isaac"
description="[DEPRECATED] An extension that allows you to load shapenet models into the scene from a local database"
authors = ["NVIDIA"]
keywords = ["kit", "shapenet", "data"]
changelog = "docs/CHANGELOG.md"
icon = "data/icon.png"
writeTarget.kit = true

[dependencies]
"omni.kit.uiapp" = {}
"omni.kit.asset_converter" = {}
"omni.kit.commands" = {}
"omni.kit.menu.utils" = {}
"omni.kit.widget.settings" = {}
"omni.physx" = {}
"omni.isaac.ui" = {}
"omni.kit.pip_archive" = {} # certifi

[[python.module]]
name = "omni.isaac.shapenet"

