[package]
title = "PhysX Vehicle"
description="Exposes PhysX vehicle authoring capability, default input control and samples."
changelog="docs/CHANGELOG.md"
repository = ""
keywords = ["physics", "physx", "vehicle"]
category = "internal"
readme = "docs/README.md"

[dependencies]
"omni.ui" = {}
"omni.kit.window.property" = {}
"omni.physx" = {}
"omni.kit.property.physx" = {}  # note: to make sure vehicle property widgets show after physx core widgets
"omni.physx.demos" = {}
"omni.physx.ui" = {}

[[python.module]]
name = "omni.physxvehicle"

[[native.plugin]]
path = "bin/*.plugin"

[[test]]
dependencies = [
   "omni.kit.renderer.core",
]
waiver = "PhysX tests are running in a separate CI pipeline. Tests are in separate extensions."