[core]
reloadable = true
order = 0

[package]
version = "1.1.0"
category = "Simulation"
title = "[Deprecated] Isaac Sim URDF Importer"
description = "This extension has been deprecated. Please use omni.importer.urdf instead."
authors = ["NVIDIA"]
repository = ""
keywords = ["isaac", "urdf", "import"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
writeTarget.kit = true

[dependencies]


[[python.module]]
name = "omni.isaac.urdf"


[[test]]
dependencies = ["omni.kit.test"]

stdoutFailPatterns.exclude = [
    "*extension object is still alive, something holds a reference on it*", # exclude warning as failure
]
