[package]
title = "PhysX Foundation"
description="PhysX 5 foundation."
changelog="docs/CHANGELOG.md"
readme = "docs/README.md"

repository = ""
keywords = ["physics", "physx", "foundation"]
category = "internal"

[dependencies]

[[native.plugin]]
path = "bin/omni.physx.foundation.plugin"

[[test]]
waiver = "PhysX tests are running in a separate CI pipeline. Tests are in separate extensions."