[package]
title = "V-HACD Convex Decompostion"
description="V-HACD Convex Decompostion"
changelog="docs/CHANGELOG.md"

authors = ["NVIDIA"]
repository = ""
keywords = ["convex", "convexdecomposition"]
category = "simulation"


[dependencies]
"omni.assets.plugins" = { }
"omni.usd.libs" = {}
"omni.usd.schema.physics" = {}
"omni.usd.schema.physx" = {}
"omni.kit.commands" = {optional=true}

[[python.module]]
name = "omni.convexdecomposition"

[[native.plugin]]
path = "bin/*.plugin"
