[core]
reloadable = true
order = 0

[package]
version = "0.2.1"
category = "Simulation"
title = "Camera Inspector"
description = "This extension can inspect and modify the properties of cameras in the scene."
authors = ["NVIDIA"]
repository = ""
keywords = ["isaac", "camera", "analyze", "inspect", "manager"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
writeTarget.kit = true

[dependencies]
"omni.physx" = {}
"omni.isaac.core" = {}
"omni.isaac.dynamic_control" = {}
"omni.isaac.ui" = {}
"omni.isaac.sensor" = {}

[[python.module]]
name = "omni.isaac.camera_inspector"