[core]
reloadable = true
order = 0

[package]
version = "2.5.1"
category = "Simulation"
title = "ROS2 Bridge"
description = "ROS2 Bridge"
authors = ["NVIDIA"]
repository = ""
keywords = ["isaac", "ROS2"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"

[dependencies]
"omni.kit.uiapp" = {}
"omni.isaac.dynamic_control" = {}
"omni.isaac.range_sensor" = {}
"omni.isaac.core" = {}
"omni.isaac.core_nodes" = {}
"omni.syntheticdata" = {}
"omni.replicator.core" = {}
"omni.usd.schema.isaac" = {}
"omni.graph" = {}
"omni.graph.tools" = {}
"omni.isaac.sensor" = {}
"usdrt.scenegraph" = {}

[settings]
exts."omni.isaac.ros2_bridge".ros_distro = "humble" # This setting specified which ros distro to fallback onto if none were sourced. 

[[python.module]]
name = "omni.isaac.ros2_bridge"

[[python.module]]
name = "foxy.rclpy"

[[python.module]]
name = "humble.rclpy"

[[python.module]]
name = "omni.isaac.ros2_bridge.tests"
public = false

[[python.module]]
name = "omni.isaac.ros2_bridge.scripts.samples.ros_samples"

[[python.module]]
name = "omni.isaac.ros2_bridge.scripts.samples.ros_moveit_sample"

[fswatcher.paths]
exclude = ["*/rclpy/*", "*/bin", "*/__pycache__/*", "*/.git/*"]

[fswatcher.patterns]
include = ["*.ogn", "*.py", "*.toml"]
exclude = ["Ogn*Database.py"]

[[test]]
dependencies = [
    "omni.graph.ui",
    "omni.isaac.wheeled_robots",
]

stdoutFailPatterns.exclude = [
    "*[Error] [omni.graph.core.plugin] /ActionGraph/ReadLidarPCL: [/ActionGraph] no prim path found for the lidar*",
    "*[Error] [omni.graph.core.plugin] /TestGraph/Template_omni_isaac_ros2_bridge_ROS2PublishJointState: [/TestGraph] Could not find target prim*",
    "*[Error] [omni.graph.core.plugin] /TestGraph/Template_omni_isaac_ros2_bridge_ROS2PublishImage: [/TestGraph] Width 0 or height 0 is not valid*",
    "*[Error] [omni.graph.core.plugin] /TestGraph/Template_omni_isaac_ros2_bridge_ROS2PublishTransformTree: [/TestGraph] Please specify atleast one target prim for the ROS pose tree component*"
]

