display_name = "Onshape Importer"

[package]
version = "0.7.0"
category = "Importer"
title = "Onshape Importer"
description = "Import Onshape Documents into Omniverse"
authors = ["NVIDIA"]
repository = ""
keywords = ["isaac"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
preview_image = "data/preview.png"
writeTarget.kit = true

[dependencies]
"omni.kit.uiapp" = {}
"omni.kit.commands" = {}
"omni.kit.window.filepicker" = {}
"omni.kit.menu.utils" = {}
"omni.kit.window.preferences" = {}
"omni.timeline" = {}
"omni.physx" = {}
"omni.kit.pip_archive" = {}

[[python.module]]
path = "pip_prebundle"

[[python.module]]
name = "omni.isaac.onshape"

