[package]
category = "hidden"
authors = ["NVIDIA"]
title = "PhysX Commands"
description="Physics commands"
repository = ""
keywords = ["physics", "physx", "commands"]

[dependencies]
"omni.physx" = {}
"omni.kit.commands" = {}
"omni.kit.usd_undo" = {}
"omni.usd" = {}

[[python.module]]
name = "omni.physxcommands"

[[test]]
waiver = "PhysX tests are running in a separate CI pipeline. Tests are in separate extensions."