[core]
reloadable = true
order = 0

[package]
version = "1.0.0"
category = "Simulation"
title = "Isaac Sim MJCF Importer"
description = "MJCF Importer for Isaac Sim"
repository = ""
keywords = ["isaac", "mjcf", "mujoco", "import"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
writeTarget.kit = true

[dependencies]



[[python.module]]
name = "omni.isaac.mjcf"

[[test]]
dependencies = ["omni.kit.test"]
