[core]
reloadable = true
order = 0

[package]
version = "3.3.2"
category = "Simulation"
title = "Isaac Sim Core"
description = "Core"
authors = ["NVIDIA"]
repository = ""
keywords = ["isaac"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true

[dependencies]
"omni.isaac.dynamic_control" = {}
"omni.isaac.core_archive" = {}
"omni.isaac.ml_archive" = {}
"omni.pip.compute" = {} # scipy
"omni.pip.cloud" = {}
"omni.physx.tensors" = {}
"omni.kit.material.library" = {} # omni.kit.material
"omni.isaac.version" = {}
"omni.warp.core" = {}


[[python.module]]
name = "omni.isaac.core"

[[python.module]]
name = "omni.isaac.core.tests"

[[test]]
timeout = 12000
dependencies = [
    "omni.hydra.rtx",                       # "omni.hydra.pxr", Can we run and pass with Storm ?
    "omni.kit.viewport.utility",
    "omni.kit.viewport.window",
    "omni.kit.primitive.mesh",
    "omni.kit.material.library",
    "omni.warp",
    "omni.isaac.sensor",
]

stdoutFailPatterns.exclude = [
    "*Invalid articulation pointer for*", # Per node tests won't have valid bundles
]

[settings]
persistent.isaac.asset_root.default = "omniverse://localhost/NVIDIA/Assets/Isaac/2023.1.1"
persistent.isaac.asset_root.nvidia = "omniverse://localhost/NVIDIA"
persistent.isaac.asset_root.isaac = "omniverse://localhost/NVIDIA/Assets/Isaac/2023.1.1/Isaac"
persistent.isaac.asset_root.cloud = "http://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/Isaac/2023.1.1"
persistent.isaac.asset_root.timeout = 10.0
